# Generated by Django 4.1.2 on 2022-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="friends_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=100)),
                ("Last_Name", models.CharField(max_length=100)),
                ("WhatsappNumber", models.CharField(max_length=100)),
                ("Phone_Number", models.CharField(max_length=100)),
            ],
        ),
    ]
